

import {
    Bell,
    Calendar,
    CheckSquare,
    Clock,
    FileText,
    Folder,
    HelpCircle,
    Home,
    Search,
    Settings,
    Target,
    Trash2,
    Users,
    Briefcase,
    Star,
} from "lucide-react";

export const config = {
    navigation: [
        {
            enabled: true,
            type: "link",
            title: "Home",
            url: "/dash",
            endpoint: "dash",
            icon: Home,
            active: true,
        },
        {
            enabled: true,
            type: "link",
            title: "Tasks",
            url: "/dash/todo",
            endpoint: "task",
            icon: CheckSquare,
            badge: 5,
            active: true,
        },
        {
            enabled: true,
            type: "link",
            title: "Planner",
            url: "/dash/planner",
            endpoint: "planner",
            icon: Calendar,
            active: true,
        },
        {
            enabled: true,
            type: "link",
            title: "Notes",
            url: "/dash/notes",
            endpoint: "notes",
            icon: FileText,
            active: true,
        },
        {
            enabled: true,
            type: "link",
            title: "Notifications",
            url: "/dash/messages",
            endpoint: "notifications",
            icon: Bell,
            badge: 3,
            active: true,
        },
        {
            enabled: true,
            type: "link",
            title: "Orion",
            url: "/dash/orion",
            endpoint: "orion",
            icon: Star,
            active: true,
        },
        {
            enabled: true,
            type: "link",
            title: "Search",
            url: "/dash/search",
            endpoint: "search",
            icon: Search,
            active: true,
        },
        {
            enabled: true,
            type: "link",
            title: "Habits",
            url: "/dash/reflect/habits",
            endpoint: "habits",
            icon: Target,
            active: true,
        },
        {
            enabled: true,
            type: "link",
            title: "Time",
            url: "/dash/time",
            endpoint: "time",
            icon: Clock,
            active: true,
        },
        {
            enabled: true,
            type: "group",
            title: "Workspaces",
            endpoint: "workspaces",
            url: "/dash/workspaces",
            icon: Users,
            active: true,
            pages: [
                {
                    enabled: true,
                    type: "link",
                    title: "Personal",
                    url: "/workspaces/personal",
                    icon: Users,
                    active: true,
                },
                {
                    enabled: true,
                    type: "link",
                    title: "Work",
                    url: "/workspaces/work",
                    icon: Briefcase,
                    active: true,
                },
                {
                    enabled: true,
                    type: "link",
                    title: "Projects",
                    url: "/workspaces/projects",
                    icon: Folder,
                    active: true,
                },
            ],
        },
        {
            enabled: true,
            type: "link",
            title: "Settings",
            url: "/dash/settings",
            endpoint: "settings",
            icon: Settings,
            active: true,
        },
        {
            enabled: true,
            type: "link",
            title: "Trash",
            url: "/dash/trash",
            endpoint: "trash",
            icon: Trash2,
            active: true,
        },
        {
            enabled: true,
            type: "link",
            title: "Help",
            url: "/dash/help",
            endpoint: "help",
            icon: HelpCircle,
            active: true,
        },
    ],

    // Available pages for breadcrumb navigation
    availablePages: {
        root: [ "dashboard", "home", "login", "signup" ],
        sections: [
            "home",
            "task",
            "planner",
            "notes",
            "notifications",
            "orion",
            "search",
            "habits",
            "time",
            "workspaces",
            "settings",
            "trash",
            "help",
        ],
        taskActions: [ "edit", "new", "details", "metadata", "schema", "stats" ],
    },

    // Sample task IDs for breadcrumb navigation
    sampleTaskIds: [
        "g765dfg6755dsf78ghsd754f6",
        "a123bcd456efg789hij012k",
        "z987yxw654vut321srq098p",
        "b246ace8dfg135hjk790lm",
        "p098onm765lkj432hgf1ed",
    ],

    // Keyboard shortcuts map
    keyboardShortcuts: {
        // Navigation
        "g h": "Go to Home",
        "g t": "Go to Tasks",
        "g p": "Go to Planner",
        "g n": "Go to Notes",

        // Creation
        "n t": "New Task",
        "n e": "New Event",
        "n p": "New Project",
        "n n": "New Note",

        // Management
        "ctrl+t": "Manage Tasks",
        "ctrl+g": "Manage Goals",
        "ctrl+r": "Create Reminder",
        "ctrl+,": "Open Settings",
        "ctrl+/": "Open Help",
    },
};




/* export const dashboard_nav = {
    header: [
        {
            active: false,
            enabled: true,
            title: "Home",
            target: '',
            url: "/",
            icon: Home,
            showInMiniNav: true,
        },
        {
            active: true,
            enabled: true,
            title: "Dashboard",
            target: 'dash',
            url: "/dash/home",
            icon: BoxesIcon,
            showInMiniNav: true,
        },
        {
            active: false,
            enabled: true,
            title: "Todo",
            target: 'todo',
            url: "/dash/todo/kanban",
            icon: LucideLaptopMinimalCheck,
            showInMiniNav: true,
            badge: ( getDataLengthSafe( tasksData ) ),
        },
        {
            active: false,
            enabled: true,
            title: "Planner",
            target: 'planner',
            url: "/dash/planner/scheduler",
            icon: CalendarIcon,
            showInMiniNav: true,
            badge: ( getDataLengthSafe( eventsData ) ),
        },
        {
            active: false,
            enabled: true,
            title: "Notes",
            target: 'notes',
            url: "/dash/notes",
            icon: Inbox,
            showInMiniNav: true,
            // badge: ( getDataLengthSafe( notesData ) ),
            badge: (
                // getDataLengthSafe( filesData ) +
                // getDataLengthSafe( foldersData ) +
                getDataLengthSafe( recentNotesData )
            ),
        },
        {
            active: false,
            enabled: false,
            title: "Habits",
            target: 'habits',
            url: "/dash/habits",
            icon: HeartPulseIcon,
            showInMiniNav: true,
        },
        {
            active: false,
            enabled: false,
            title: "Reflect",
            target: 'reflect',
            url: "/dash/reflect",
            icon: LucideMessageCircleMore,
            showInMiniNav: false,
        },
        {
            active: false,
            enabled: true,
            title: "Stats",
            target: 'stats',
            url: "/dash/stats",
            icon: GlassesIcon,
            showInMiniNav: true,
            badge: (
                utils.val.isValidArray( notifications, true ) && utils.val.isValidArray( reminders, true )
                    ? ( `${ getDataLengthSafe( notifications ) } / ${ getDataLengthSafe( reminders ) }` )
                    : ( null )
            ),
        },
        {
            active: false,
            enabled: true,
            title: "Journal",
            target: 'journal',
            url: "/dash/journal",
            icon: BookHeartIcon,
            showInMiniNav: true,
        },
        {
            active: false,
            enabled: true,
            title: "Time",
            target: 'time',
            url: "/dash/time",
            icon: Clock,
            showInMiniNav: true,
        },
        {
            active: false,
            enabled: true,
            title: "Orion",
            target: 'orion',
            url: "/dash/orion",
            icon: Sparkles,
            showInMiniNav: false,
        },
    ],
    footer: [
        {
            active: false,
            enabled: false,
            title: "Search",
            target: 'search',
            url: "/dash/search",
            icon: Search,
            showInMiniNav: false,
        },
        {
            active: false,
            enabled: true,
            title: "Workspaces",
            url: "/dash/workspaces",
            icon: Blocks,
            showInMiniNav: true,
            target: 'workspaces',
            badge: ( getDataLengthSafe( workspacesData ) ),
        },
        {
            active: false,
            enabled: true,
            title: "Messages",
            target: 'messages',
            url: "/dash/messages",
            icon: AlertCircleIcon,
            showInMiniNav: true,
            badge: (
                utils.val.isValidArray( reminderData, true )
                    ? ( getDataLengthSafe( reminderData ) )
                    : ( null )
            ),
        },
        {
            active: false,
            enabled: false,
            title: "Notifications",
            target: 'notifications',
            url: "/dash/notifications",
            icon: BellRing,
            showInMiniNav: false,
            badge: (
                utils.val.isValidArray( statsData, true )
                    ? ( getDataLengthSafe( statsData ) )
                    : ( null )
            ),
        },
        {
            enabled: true,
            title: "Trash",
            url: "/dash/trash",
            icon: Trash2,
            showInMiniNav: false,
            target: 'trash',
            // badge: ( getDataLengthSafe( workspacesData ) ),
            badge: ( getTrash() ),
            active: false,
        },
        {
            enabled: true,
            title: "Settings",
            url: "/dash/settings",
            icon: Settings2,
            showInMiniNav: true,
            target: 'settings',
            // badge: "10",
            active: false,
        },
        {
            enabled: true,
            title: "Help",
            url: "/dash/help",
            icon: MessageCircleQuestion,
            showInMiniNav: false,
            target: 'help',
            active: false,
        },
    ],
}; */